{
  "formatVersion": "1.1",
  "component": {
    "group": "packer",
    "module": "packer-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6uhphmwcwvfphmj7uv2fn7qbii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packer-0.2.0.jar",
          "url": "packer-0.2.0.jar",
          "size": 27115,
          "sha512": "9f0035f67fe39512b0f731e0d2fb6cc76ccb851146ac46872ba095938efc927d745b779a3ec103193621b8a754924d1a4c8fd642c2597be3ba9ea9463b6aba80",
          "sha256": "dce598d786cdb7e33c68e31fa9c8108ec942241ce7a30c907209cd33b4e6ce9c",
          "sha1": "53be034ad876d980be91dd5bb4d81c4d445f7f51",
          "md5": "f1d0969279eebf4cca55390088e72117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "packer-0.2.0.jar",
          "url": "packer-0.2.0.jar",
          "size": 27115,
          "sha512": "9f0035f67fe39512b0f731e0d2fb6cc76ccb851146ac46872ba095938efc927d745b779a3ec103193621b8a754924d1a4c8fd642c2597be3ba9ea9463b6aba80",
          "sha256": "dce598d786cdb7e33c68e31fa9c8108ec942241ce7a30c907209cd33b4e6ce9c",
          "sha1": "53be034ad876d980be91dd5bb4d81c4d445f7f51",
          "md5": "f1d0969279eebf4cca55390088e72117"
        }
      ]
    }
  ]
}
